# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrains_Sokoban_Basys3.xdc

# IP: ip/Memoria_Numeros/Memoria_Numeros.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Memoria_Numeros || ORIG_REF_NAME==Memoria_Numeros} -quiet] -quiet

# IP: ip/Memoria_Letras/Memoria_Letras.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Memoria_Letras || ORIG_REF_NAME==Memoria_Letras} -quiet] -quiet

# IP: ip/Memoria_Mensajes/Memoria_Mensajes.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Memoria_Mensajes || ORIG_REF_NAME==Memoria_Mensajes} -quiet] -quiet

# IP: ip/Memoria_Soluciones/Memoria_Soluciones.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Memoria_Soluciones || ORIG_REF_NAME==Memoria_Soluciones} -quiet] -quiet

# IP: ip/Memoria_Fases/Memoria_Fases.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Memoria_Fases || ORIG_REF_NAME==Memoria_Fases} -quiet] -quiet

# IP: ip/Memoria_Tablero/Memoria_Tablero.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Memoria_Tablero || ORIG_REF_NAME==Memoria_Tablero} -quiet] -quiet

# IP: ip/Memoria_Sprites/Memoria_Sprites.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Memoria_Sprites || ORIG_REF_NAME==Memoria_Sprites} -quiet] -quiet

# XDC: c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Numeros/Memoria_Numeros_ooc.xdc

# XDC: c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Letras/Memoria_Letras_ooc.xdc

# XDC: c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Mensajes/Memoria_Mensajes_ooc.xdc

# XDC: c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Soluciones/Memoria_Soluciones_ooc.xdc

# XDC: c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Fases/Memoria_Fases_ooc.xdc

# XDC: c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Tablero/Memoria_Tablero_ooc.xdc

# XDC: c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Sprites/Memoria_Sprites_ooc.xdc
