# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.runs/synth_1/Top_proyecto.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {Common 17-576}  -string {{WARNING: [Common 17-576] 'use_project_ipc' is deprecated. This option is deprecated and no longer used.}}  -suppress 
set_msg_config  -id {IP_Flow 19-4067}  -string {{WARNING: [IP_Flow 19-4067] Ignoring invalid widget type specified checkbox.Providing a default widget}}  -suppress 
set_msg_config  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. Failed to delete one or more files in run directory C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/Proyecto FPGA/Desarrollo/Proyecto_Sokoban/Proyecto_Sokoban.runs/synth_1}}  -suppress 
set_msg_config  -id {Vivado 12-3523}  -string {{WARNING: [Vivado 12-3523] Attempt to change 'Component_Name' from 'Memoria_Sprites' to 'Memoria_Sprites' is not allowed and is ignored.}}  -suppress 
set_msg_config  -id {Vivado 12-3523}  -string {{WARNING: [Vivado 12-3523] Attempt to change 'Component_Name' from 'Memoria_Tablero' to 'Memoria_Tablero' is not allowed and is ignored.}}  -suppress 
set_msg_config  -id {Vivado 12-3523}  -string {{WARNING: [Vivado 12-3523] Attempt to change 'Component_Name' from 'Memoria_Fases' to 'Memoria_Fases' is not allowed and is ignored.}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.cache/wt [current_project]
set_property parent.project_path C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/memoria_fases.coe
add_files C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/memoria_letras.coe
add_files C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/memoria_mensajes.coe
add_files C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/memoria_numeros.coe
add_files C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/memoria_solu.coe
add_files C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/memoria_sprites.coe
read_vhdl -library xil_defaultlib {
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/Comparador.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/Contador.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/Dibuja.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/Div_Frec_Pixel.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/Driver_VGA.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/Genera_Color.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/Maq_Estados_Juego.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/cont_digito_10.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/cont_digito_6.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/contador_movimientos.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/div_frec_4.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/logica_fin_tiempo.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/mux_sprites.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/top_contador.vhd
  C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/new/Top_Proyecto.vhd
}
read_ip -quiet C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/ip/Memoria_Numeros/Memoria_Numeros.xci
set_property used_in_implementation false [get_files -all c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Numeros/Memoria_Numeros_ooc.xdc]

read_ip -quiet C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/ip/Memoria_Letras/Memoria_Letras.xci
set_property used_in_implementation false [get_files -all c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Letras/Memoria_Letras_ooc.xdc]

read_ip -quiet C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/ip/Memoria_Mensajes/Memoria_Mensajes.xci
set_property used_in_implementation false [get_files -all c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Mensajes/Memoria_Mensajes_ooc.xdc]

read_ip -quiet C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/ip/Memoria_Soluciones/Memoria_Soluciones.xci
set_property used_in_implementation false [get_files -all c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Soluciones/Memoria_Soluciones_ooc.xdc]

read_ip -quiet C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/ip/Memoria_Fases/Memoria_Fases.xci
set_property used_in_implementation false [get_files -all c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Fases/Memoria_Fases_ooc.xdc]

read_ip -quiet C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/ip/Memoria_Tablero/Memoria_Tablero.xci
set_property used_in_implementation false [get_files -all c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Tablero/Memoria_Tablero_ooc.xdc]

read_ip -quiet C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/sources_1/ip/Memoria_Sprites/Memoria_Sprites.xci
set_property used_in_implementation false [get_files -all c:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.gen/sources_1/ip/Memoria_Sprites/Memoria_Sprites_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/constrs_1/new/constrains_Sokoban_Basys3.xdc
set_property used_in_implementation false [get_files C:/Users/Leon/Documents/Universidad/3_GIERM/Sist_Electronicos/ENTREGA_Proyecto_FPGA/Proyecto_FPGA_Sokoban/Proyecto_Sokoban/Proyecto_Sokoban.srcs/constrs_1/new/constrains_Sokoban_Basys3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top_proyecto -part xc7a35tcpg236-1 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_proyecto.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_proyecto_utilization_synth.rpt -pb Top_proyecto_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
